version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ../assignments:/var/www/html/assignments
      - ../project:/var/www/html/project
      - ./logs/nginx:/var/log/nginx/
  php:
    image: php:fpm-alpine
    networks:
      - internal
    volumes:
      - ../:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
  mysql:
    image: mysql
    networks:
      - internal
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  internal:
    driver: bridge

