version: "3"
services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app_network
    volumes:
      - ../assignments:/var/www/html/assignments
      - ../project:/var/www/html/project
      - ./logs/nginx:/var/log/nginx/
  php:
    container_name: php
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - app_network
      - db_network
    volumes:
      - ../:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
  mysql:
    container_name: mysql
    image: mysql
    networks:
      - db_network
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
networks:
  app_network:
  db_network:
